CREATE TABLE `gm_bookmarks` 
( `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT , 
 `quote` VARCHAR(255) NOT NULL , 
 `author` VARCHAR(255) NOT NULL , 
 `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
 `updated_at` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
 PRIMARY KEY (`id`), 
 INDEX `idx_author` (`author`), UNIQUE `idx_quote_uniqie` (`quote`)
) 
 ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
 INSERT INTO `gm_bookmarks` (`id`, `quote`, `author`) VALUES
(1, 'There are only two kinds of languages: the ones people complain about and the ones nobody uses.', 'Bjarne Stroustrup'),
(3, 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'Martin Fowler'),
(4, 'First, solve the problem. Then, write the code.', 'John Johnson'),
(5, 'Java is to JavaScript what car is to Carpet.', 'Chris Heilmann'),
(6, 'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.', 'John Woods'),
(7, "I'm not a great programmer; I'm just a good programmer with great habits.", 'Kent Beck'),
(8, 'Truth can only be found in one place: the code.', 'Robert C. Martin'),
(9, "If you have to spend effort looking at a fragment of code and figuring out what it's doing, then you should extract it into a function and name the function after the 'what'.", 'Martin Fowler'),
(10, 'The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times; premature optimization is the root of all evil (or at least most of it) in programming.', 'Donald Knuth'),
(11, 'SQL, Lisp, and Haskell are the only programming languages that I’ve seen where one spends more time thinking than typing.', 'Philip Greenspun'),
(12, 'Deleted code is debugged code.', 'Jeff Sickel'),
(13, 'There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies and the other way is to make it so complicated that there are no obvious deficiencies.', 'C.A.R. Hoare'),
(14, 'Simplicity is prerequisite for reliability.', 'Edsger W. Dijkstra'),
(15, 'There are only two hard things in Computer Science: cache invalidation and naming things.', 'Phil Karlton'),
(16, 'Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 'Bill Gates');

/*
    Creation Bookmarks Table
    Date: 09/08/2021 19:57:05
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for gm_countries
-- ----------------------------
DROP TABLE IF EXISTS `gm_countries`;
CREATE TABLE `gm_countries`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `iso_2` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `continent` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `name` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `nationality_name` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `iso_name` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `long_name` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `flag` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `iso_3` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `un_member` tinyint NULL DEFAULT NULL,
  `numeric_code` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `calling_code` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `cctld` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `population` int NULL DEFAULT NULL,
  `total_area` int NULL DEFAULT NULL,
  `land_area` int NULL DEFAULT NULL,
  `water_area` int NULL DEFAULT NULL,
  `published` int NOT NULL DEFAULT 0,
  `license_plate_code` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `capital_city` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `largest_cities` json,
  `bordering_countries_regions` json,
  `regions` json,
  `natural_resources` json,
  `coastline_length` decimal (10,2),
  `annual‐crop_land_fraction` decimal (10,9),
  `population_density` decimal (10,4),
  `population_growth` decimal (10,7),
  `life_expectancy` decimal (10,7),
  `annual_births` int NULL DEFAULT NULL,
  `annual_deaths` int NULL DEFAULT NULL,
  `median_age` decimal(10,7),
  `gdp` bigint,
  `gdp_at_parity` bigint,
  `real_gdp` bigint,
  `gdp_per_capita` decimal(10,2),
  `gdp_real_growth` decimal(10,7),
  `gini_index` decimal(10,9),
  `consumer_price_inflation` decimal(10,7),
  `unemployment_rate` decimal(10,7),
  `labor_force` bigint,
  `employment_in_agriculture` bigint,
  `employment_in_industry` bigint,
  `employment_in_services` bigint,
  `employment` bigint,
  `language_fractions` json,
  `ethnic_mix` json,
  `religions` json,
  `literacy_rate` decimal(10,7),
  `internet_usage` int NULL DEFAULT NULL,
  `mobile_cellular_subscriptions` int NULL DEFAULT NULL,
  `telephone_lines` int NULL DEFAULT NULL,
  `fixed_broadband_internet_subscribers` int NULL DEFAULT NULL,
  `average_broadband_upload_rate` decimal (10,6),
  `average_broadband_download_rate` decimal (10,6),
  `secure_internet_servers` int NULL DEFAULT NULL,
  `IP_addresses` bigint,
  `total_vehicles_in_use` int NULL DEFAULT NULL,
  `total_road_length` decimal (10,2),
  `primary_school_students` int NULL DEFAULT NULL,
  `secondary_school_students` int NULL DEFAULT NULL,
  `tertiary_school_students` int NULL DEFAULT NULL,
  `total_students` int NULL DEFAULT NULL,
  `total_teachers` int NULL DEFAULT NULL,
  `primary_school_student-teacher_ratio` decimal (10,7),
  `secondary_school_student-teacher_ratio` decimal (10,7),
  `public_education_spending_percent_of_gdp` decimal (10,7),
  `physicians_per_capita` decimal (10,9),
  `hospital_beds` decimal (10,9),
  `Human_Development_Index_health` decimal (10,9), 
  `Human_Development_Index_education` decimal (10,9),
  `Human_Development_Index_living_standards` decimal (10,9),
  `Human_Development_Index_total` decimal (10,9),
  `shared_border_lengths` json,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `iso_3`(`iso_3`) USING BTREE,
  INDEX `iso_2`(`iso_2`) USING BTREE,
  INDEX `continent`(`continent`) USING BTREE,
  INDEX `published`(`published`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 243 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;